// src/renderer/components/TimelineSpace/Compose.vue
<template>
  <div class="compose">
    <Quote v-if="inReplyTo" :message="inReplyTo" @close="clearReply" />
    <Quote v-if="quoteTo" :message="quoteTo" @close="clearQuote" />
    <el-form :model="form" class="compose-form">
      <el-input v-model="form.spoiler" class="spoiler" :placeholder="$t('compose.cw')" v-if="cw" />
      <el-input v-model="form.status" type="textarea" :autosize="{ minRows: 2 }" :placeholder="$t('compose.status')" ref="statusRef" />
      <div class="preview" ref="previewRef">
        <div class="image-wrapper" v-for="media in attachments" :key="media.id">
          <img :src="media.preview_url" class="preview-image" />
          <el-button class="remove-image" link @click="removeAttachment(media)"><font-awesome-icon icon="circle-xmark" /></el-button>
        </div>
      </div>
      <div class="nsfw" v-if="attachments.length > 0">
        <el-checkbox v-model="nsfw">{{ $t('compose.footer.change_sensitive') }}</el-checkbox>
      </div>
      <div class="poll" v-if="poll.options.length > 0">
        <ul class="options-list">
          <li class="option" v-for="(option, index) in poll.options" :key="index">
            <el-radio :disabled="true" :label="index">
              <el-input :placeholder="`Choice ${index}`" v-model="poll.options[index]" size="small"></el-input>
              <el-button class="remove-poll" link size="small" @click="removePollOption(index)"
                ><font-awesome-icon icon="xmark"
              /></el-button>
            </el-radio>
          </li>
        </ul>
        <el-button class="add-poll" type="info" size="small" @click="addPollOption">{{ $t('compose.poll.add_choice') }}</el-button>
        <el-select v-model="poll.expires_in" size="small" value-key="value">
          <el-option v-for="exp in expiresList" :key="exp.value" :label="exp.label" :value="exp.value"> </el-option>
        </el-select>
      </div>
      <div class="form-footer">
        <el-button-group class="tool-buttons">
          <el-button link size="default" @click="selectImage">
            <font-awesome-icon icon="camera" />
          </el-button>
          <input name="image" type="file" class="image-input" ref="imageRef" @change="onChangeImage" />
          <el-button link size="default" @click="togglePoll">
            <font-awesome-icon icon="square-poll-horizontal" />
          </el-button>
          <div>
            <el-dropdown trigger="click" @command="changeVisibility">
              <el-button size="default" link :title="$t('compose.footer.change_visibility')">
                <font-awesome-icon :icon="visibilityIcon" />
              </el-button>
              <template #dropdown>
                <el-dropdown-menu>
                  <el-dropdown-item :command="visibilityList.Public.key">
                    <font-awesome-icon icon="globe" class="privacy-icon" />
                    {{ $t(visibilityList.Public.name) }}
                  </el-dropdown-item>
                  <el-dropdown-item :command="visibilityList.Unlisted.key">
                    <font-awesome-icon icon="unlock" class="privacy-icon" />
                    {{ $t(visibilityList.Unlisted.name) }}
                  </el-dropdown-item>
                  <el-dropdown-item :command="visibilityList.Private.key">
                    <font-awesome-icon icon="lock" class="privacy-icon" />
                    {{ $t(visibilityList.Private.name) }}
                  </el-dropdown-item>
                  <el-dropdown-item :command="visibilityList.Direct.key">
                    <font-awesome-icon icon="envelope" class="privacy-icon" size="sm" />
                    {{ $t(visibilityList.Direct.name) }}
                  </el-dropdown-item>
                </el-dropdown-menu>
              </template>
            </el-dropdown>
          </div>
          <el-popover placement="top" width="0" :visible="emojiVisible" popper-class="new-toot-emoji-picker">
            <picker
              v-if="emojiData !== null"
              :data="emojiData"
              set="twitter"
              :autoFocus="true"
              @select="selectEmoji"
              :perLine="7"
              :emojiSize="24"
              :showPreview="false"
              :emojiTooltip="true"
            />
            <template #reference>
              <el-button link size="default" @click="emojiVisible = !emojiVisible">
                <font-awesome-icon :icon="['far', 'face-smile']" />
              </el-button>
            </template>
          </el-popover>
          <el-button link size="default" @click="cw = !cw"> CW </el-button>
        </el-button-group>
        <div class="actions-group">
          <span>{{ statusChars }}</span>
          <el-button type="primary" @click="post" :loading="loading"> {{ $t('compose.toot') }} </el-button>
        </div>
      </div>
    </el-form>
    <receive-drop v-if="droppableVisible"></receive-drop>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, computed, ref, onMounted, onBeforeUnmount, watch } from 'vue'
import { useRoute } from 'vue-router'
import generator, { Entity, MegalodonInterface } from 'megalodon'
import emojiDefault from 'emoji-mart-vue-fast/data/all.json'
import { Picker, EmojiIndex } from 'emoji-mart-vue-fast/src'
import { useI18next } from 'vue3-i18next'
import { ElMessage } from 'element-plus'
import { useStore } from '@/store'
import { MyWindow } from '~/src/types/global'
import { LocalAccount } from '~/src/types/localAccount'
import { LocalServer } from '~/src/types/localServer'
import visibilityList from '~/src/constants/visibility'
import { MUTATION_TYPES } from '@/store/TimelineSpace/Compose'
import ReceiveDrop from './ReceiveDrop.vue'
import Quote from './Compose/Quote.vue'

type Expire = {
  label: string
  value: number
}

export default defineComponent({
  name: 'Compose',
  components: { Picker, ReceiveDrop, Quote },
  setup() {
    const route = useRoute()
    const store = useStore()
    const i18n = useI18next()
    const space = 'TimelineSpace/Compose'
    const win = (window as any) as MyWindow

    const id = computed(() => parseInt(route.params.id as string))
    const userAgent = computed(() => store.state.App.userAgent)
    const visibilityIcon = computed(() => {
      switch (visibility.value) {
        case visibilityList.Public.key:
          return 'globe'
        case visibilityList.Unlisted.key:
          return 'unlock'
        case visibilityList.Private.key:
          return 'lock'
        case visibilityList.Direct.key:
          return 'envelope'
        default:
          return 'globe'
      }
    })
    const expiresList = reactive<Array<Expire>>([
      {
        label: i18n.t('compose.poll.expires.5_minutes'),
        value: 60 * 5
      },
      {
        label: i18n.t('compose.poll.expires.30_minutes'),
        value: 60 * 30
      },
      {
        label: i18n.t('compose.poll.expires.1_hour'),
        value: 3600
      },
      {
        label: i18n.t('compose.poll.expires.6_hours'),
        value: 3600 * 6
      },
      {
        label: i18n.t('compose.poll.expires.1_day'),
        value: 3600 * 24
      },
      {
        label: i18n.t('compose.poll.expires.3_days'),
        value: 3600 * 24 * 3
      },
      {
        label: i18n.t('compose.poll.expires.7_days'),
        value: 3600 * 24 * 7
      }
    ])

    const emojiData = ref<EmojiIndex | null>(null)
    const client = ref<MegalodonInterface | null>(null)
    const form = reactive({
      status: '',
      spoiler: ''
    })
    const attachments = ref<Array<Entity.Attachment | Entity.AsyncAttachment>>([])
    const cw = ref<boolean>(false)
    const visibility = ref(visibilityList.Public.key)
    const nsfw = ref<boolean>(false)
    const inReplyTo = computed(() => store.state.TimelineSpace.Compose.inReplyTo)
    const quoteTo = computed(() => store.state.TimelineSpace.Compose.quoteTo)
    const poll = reactive<{ options: Array<string>; expires_in: number }>({
      options: [],
      expires_in: 86400
    })

    const loading = ref<boolean>(false)
    const emojiVisible = ref<boolean>(false)
    const imageRef = ref<any>(null)
    const statusRef = ref<any>(null)

    const dropTarget = ref<any>(null)
    const droppableVisible = ref<boolean>(false)

    const maxStatusChars = ref<number>(500)
    const statusChars = computed(() => maxStatusChars.value - (form.status.length + form.spoiler.length))

    onMounted(async () => {
      const [a, s]: [LocalAccount, LocalServer] = await win.ipcRenderer.invoke('get-local-account', id.value)
      const c = generator(s.sns, s.baseURL, a.accessToken, userAgent.value)
      client.value = c

      const credentials = await c.verifyAccountCredentials()
      if (credentials.data.source) {
        visibility.value = credentials.data.source.privacy
        nsfw.value = credentials.data.source.sensitive
      }

      const instance = await c.getInstance()
      if (instance.data.max_toot_chars) {
        maxStatusChars.value = instance.data.max_toot_chars
      }

      const emojis = await c.getInstanceCustomEmojis()
      const customEmojis = emojis.data
        .map(emoji => {
          return {
            name: `:${emoji.shortcode}:`,
            image: emoji.url
          }
        })
        .filter((e, i, array) => {
          return array.findIndex(ar => e.name === ar.name) === i
        })
        .map(e => ({
          name: e.name,
          short_names: [e.name],
          text: e.name,
          emoticons: [],
          keywords: [e.name],
          imageUrl: e.image
        }))
      emojiData.value = new EmojiIndex(emojiDefault, { custom: customEmojis })
      ;(window as any).addEventListener('dragenter', onDragEnter)
      ;(window as any).addEventListener('dragleave', onDragLeave)
      ;(window as any).addEventListener('dragover', onDragOver)
      ;(window as any).addEventListener('drop', handleDrop)
    })

    onBeforeUnmount(() => {
      ;(window as any).removeEventListener('dragenter', onDragEnter)
      ;(window as any).removeEventListener('dragleave', onDragLeave)
      ;(window as any).removeEventListener('dragover', onDragOver)
      ;(window as any).removeEventListener('drop', handleDrop)
    })

    watch(inReplyTo, current => {
      if (current) {
        form.status = `@${current.account.acct} `
      }
    })

    const post = async () => {
      if (!client.value) {
        return
      }
      let options = {
        visibility: visibility.value
      }
      try {
        loading.value = true
        if (attachments.value.length > 0) {
          options = Object.assign(options, {
            media_ids: attachments.value.map(m => m.id)
          })
          if (nsfw.value) {
            options = Object.assign(options, {
              sensitive: nsfw.value
            })
          }
        }
        if (form.spoiler.length > 0) {
          options = Object.assign(options, {
            spoiler_text: form.spoiler
          })
        }
        if (inReplyTo.value) {
          options = Object.assign(options, {
            in_reply_to_id: inReplyTo.value?.id
          })
        }
        if (quoteTo.value) {
          options = Object.assign(options, {
            quote_id: quoteTo.value?.id
          })
        }

        if (poll.options.length > 0) {
          options = Object.assign(options, {
            poll: poll
          })
        }

        await client.value.postStatus(form.status, options)
        clear()
      } catch (err) {
        console.error(err)
      } finally {
        loading.value = false
      }
    }

    const clear = () => {
      form.status = ''
      form.spoiler = ''
      attachments.value = []
      cw.value = false
      emojiVisible.value = false
      store.commit(`${space}/${MUTATION_TYPES.CLEAR_REPLY_TO_ID}`)
      poll.options = []
    }

    const selectImage = () => {
      imageRef?.value?.click()
    }

    const onChangeImage = async (e: Event) => {
      const target = e.target as HTMLInputElement
      const file = target.files?.item(0)
      if (file === null || file === undefined) {
        return
      }
      await uploadImage(file)
    }

    const uploadImage = async (file: File) => {
      if (!client.value) {
        return
      }
      try {
        loading.value = true
        const res = await client.value.uploadMedia(file)
        attachments.value = [...attachments.value, res.data]
      } catch (err) {
        console.error(err)
      } finally {
        loading.value = false
      }
    }

    const removeAttachment = async (attachment: Entity.Attachment | Entity.AsyncAttachment) => {
      attachments.value = attachments.value.filter(e => e.id !== attachment.id)
    }

    const selectEmoji = emoji => {
      if (!statusRef.value) {
        return
      }
      const current = statusRef.value?.textarea.selectionStart
      if (emoji.native) {
        form.status = form.status.slice(0, current) + emoji.native + form.status.slice(current)
      } else {
        form.status = form.status.slice(0, current) + emoji.name + form.status.slice(current)
      }
      emojiVisible.value = false
    }

    const changeVisibility = (value: 'public' | 'unlisted' | 'private' | 'direct') => {
      visibility.value = value
    }

    const togglePoll = () => {
      if (poll.options.length > 0) {
        poll.options = []
      } else {
        poll.options = ['', '']
      }
    }

    const addPollOption = () => {
      poll.options = [...poll.options, '']
    }

    const removePollOption = (index: number) => {
      poll.options = poll.options.filter((_, i) => i !== index)
    }

    const handleDrop = (e: DragEvent) => {
      e.preventDefault()
      e.stopPropagation()
      droppableVisible.value = false
      if (e.dataTransfer?.files.item(0) === null || e.dataTransfer?.files.item(0) === undefined) {
        return false
      }
      const file = e.dataTransfer?.files.item(0)
      if (file === null || (!file.type.includes('image') && !file.type.includes('video'))) {
        ElMessage({
          message: i18n.t('validation.compose.attach_image'),
          type: 'error'
        })
        return false
      }
      uploadImage(file).catch(err => {
        console.error(err)
        ElMessage({
          message: i18n.t('message.attach_error'),
          type: 'error'
        })
      })
      return false
    }
    const onDragEnter = (e: DragEvent) => {
      if (e.dataTransfer && e.dataTransfer.types.indexOf('Files') >= 0) {
        dropTarget.value = e.target
        droppableVisible.value = true
      }
    }
    const onDragLeave = (e: DragEvent) => {
      if (e.target === dropTarget.value) {
        droppableVisible.value = false
      }
    }
    const onDragOver = (e: DragEvent) => {
      e.preventDefault()
    }

    const clearReply = () => {
      store.commit(`${space}/${MUTATION_TYPES.CLEAR_REPLY_TO_ID}`)
    }

    const clearQuote = () => {
      store.commit(`${space}/${MUTATION_TYPES.CLEAR_QUOTE_TO}`)
    }

    return {
      form,
      post,
      imageRef,
      selectImage,
      onChangeImage,
      loading,
      attachments,
      removeAttachment,
      emojiData,
      selectEmoji,
      statusRef,
      emojiVisible,
      cw,
      visibilityList,
      visibilityIcon,
      changeVisibility,
      nsfw,
      poll,
      togglePoll,
      expiresList,
      addPollOption,
      removePollOption,
      droppableVisible,
      inReplyTo,
      quoteTo,
      clearReply,
      clearQuote,
      statusChars
    }
  }
})
</script>

<style lang="scss" scoped>
.compose {
  height: auto;
  width: 100%;
  box-sizing: border-box;

  .compose-form {
    height: calc(100% - 24px);

    .spoiler {
      padding-bottom: 8px;
    }
  }

  .compose-form :deep(.el-textarea__inner) {
    color: var(--theme-primary-color);
    background-color: var(--theme-background-color);
    box-shadow: 0 0 0 1px var(--theme-border-color, var(--theme-border-color)) inset;
  }

  .compose-form :deep(.el-input__wrapper) {
    background-color: var(--theme-background-color);
    box-shadow: 0 0 0 1px var(--theme-border-color, var(--theme-border-color)) inset;
  }

  .compose-form :deep(.el-input__inner) {
    color: var(--theme-primary-color);
  }

  .preview {
    box-sizing: border-box;
    display: flex;
    flex-flow: row wrap;

    .image-wrapper {
      position: relative;
      display: flex;
      min-width: 10%;
      height: 80px;
      margin: 4px;

      .preview-image {
        width: 80px;
        height: 80px;
        object-fit: cover;
        border: 0;
        border-radius: 8px;
      }

      .remove-image {
        position: absolute;
        top: 2px;
        left: 2px;
        padding: 0;
        cursor: pointer;
        font-size: 1.5rem;

        .fa-icon {
          font-size: 0.9rem;
          width: auto;
          height: 1em;
          max-width: 100%;
          max-height: 100%;
        }
      }
    }
  }

  .poll {
    .options-list {
      list-style: none;
      padding-left: 16px;

      .poll-option {
        line-height: 38px;

        .remove-poll {
          margin-left: 4px;
        }
      }
    }

    .add-poll {
      margin: 0 4px 0 40px;
    }
  }

  .poll :deep(.el-input__inner) {
    box-shadow: none;
  }

  .form-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: 4px;

    .tool-buttons {
      display: flex;

      button {
        margin-right: 8px;
      }

      .image-input {
        display: none;
      }
    }

    .actions-group {
      span {
        margin-right: 8px;
        color: var(--theme-secondary-color);
      }
    }
  }
}

.privacy-icon {
  margin-right: 4px;
}
</style>

<style lang="scss">
.new-toot-emoji-picker {
  background-color: transparent !important;
  border: none !important;

  .el-popper__arrow {
    display: none;
  }
}
</style>

// renderer/components/compose/Compose.tsx
import { ChangeEvent, Dispatch, SetStateAction, useCallback, useEffect, useRef, useState } from 'react'
import { FormattedMessage, useIntl } from 'react-intl'
import {
  FaEnvelope,
  FaFaceLaughBeam,
  FaGlobe,
  FaListCheck,
  FaLock,
  FaLockOpen,
  FaPaperPlane,
  FaPaperclip,
  FaPencil,
  FaXmark
} from 'react-icons/fa6'
import { Entity, MegalodonInterface } from 'megalodon'
import { useToast } from '@/provider/toast'
import Picker from '@emoji-mart/react'
import { data } from '@/utils/emojiData'
import EditMedia from './EditMedia'
import {
  Button,
  Checkbox,
  IconButton,
  Input,
  List,
  ListItem,
  Option,
  Popover,
  PopoverContent,
  PopoverHandler,
  Radio,
  Select,
  Switch,
  Textarea
} from '@material-tailwind/react'

type Props = {
  client: MegalodonInterface
  in_reply_to?: Entity.Status
}

type Poll = {
  options: Array<string>
  expires_in: number
  multiple: boolean
}

export default function Compose(props: Props) {
  const [body, setBody] = useState('')
  const [visibility, setVisibility] = useState<'public' | 'unlisted' | 'private' | 'direct'>('public')
  const [cw, setCW] = useState(false)
  const [spoiler, setSpoiler] = useState('')
  const [attachments, setAttachments] = useState<Array<Entity.Attachment | Entity.AsyncAttachment>>([])
  const [poll, setPoll] = useState<Poll | null>(null)
  const [loading, setLoading] = useState(false)
  const [editMedia, setEditMedia] = useState<Entity.Attachment>()
  const [maxCharacters, setMaxCharacters] = useState<number | null>(null)
  const [remaining, setRemaining] = useState<number | null>(null)
  const [popoverVisibility, setPopoverVisibility] = useState(false)
  const [popoverEmoji, setPopoverEmoji] = useState(false)

  const { formatMessage } = useIntl()
  const uploaderRef = useRef(null)
  const showToast = useToast()
  const textareaRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!props.client) return
    const f = async () => {
      const instance = await props.client.getInstance()
      if (instance.data.configuration.statuses.max_characters) {
        setMaxCharacters(instance.data.configuration.statuses.max_characters)
      }
    }
    f()
  }, [props.client])

  useEffect(() => {
    if (!cw) {
      setSpoiler('')
    }
  }, [cw])

  useEffect(() => {
    if (props.in_reply_to) {
      const f = async () => {
        const myself = await props.client.verifyAccountCredentials()
        const mentionAccounts = [props.in_reply_to.account.acct, ...props.in_reply_to.mentions.map(a => a.acct)]
          .filter((a, i, self) => self.indexOf(a) === i)
          .filter(a => a !== myself.data.username)
        setBody(`${mentionAccounts.map(m => `@${m}`).join(' ')} `)
        setVisibility(props.in_reply_to.visibility)
      }
      f()
    }
  }, [props.in_reply_to])

  useEffect(() => {
    if (maxCharacters) {
      setRemaining(maxCharacters - body.length - spoiler.length)
    }
  }, [maxCharacters, body, spoiler])

  const post = async () => {
    if (body.length === 0) return
    let options = { visibility: visibility }
    if (props.in_reply_to) {
      options = Object.assign({}, options, {
        in_reply_to_id: props.in_reply_to.id
      })
    }
    if (cw) {
      options = Object.assign({}, options, {
        spoiler_text: spoiler
      })
    }
    if (attachments.length > 0) {
      options = Object.assign({}, options, {
        media_ids: attachments.map(m => m.id)
      })
    }
    const sensitive = document.getElementById('sensitive') as HTMLInputElement
    if (sensitive && sensitive.checked) {
      options = Object.assign({}, options, {
        sensitive: sensitive.checked
      })
    }
    if (poll && poll.options.length > 0) {
      options = Object.assign({}, options, {
        poll: poll
      })
    }
    setLoading(true)
    try {
      await props.client.postStatus(body, options)
      reset()
    } catch (err) {
      console.error(err)
      showToast({ text: formatMessage({ id: 'alert.compose.post_failed' }), type: 'failure' })
    } finally {
      setLoading(false)
    }
  }

  const reset = () => {
    setBody('')
    setSpoiler('')
    setCW(false)
    setAttachments([])
    setPoll(null)
    setMaxCharacters(null)
  }

  const handleKeyPress = useCallback(
    (event: KeyboardEvent) => {
      if ((event.ctrlKey === true && event.key === 'Enter') || (event.metaKey === true && event.key === 'Enter')) {
        post()
      }
    },
    [post]
  )

  useEffect(() => {
    textareaRef.current?.addEventListener('keydown', handleKeyPress)

    return () => {
      textareaRef.current?.removeEventListener('keydown', handleKeyPress)
    }
  }, [handleKeyPress])

  const selectFile = () => {
    if (uploaderRef.current) {
      uploaderRef.current.click()
    }
  }

  const fileChanged = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.item(0)
    if (file === null || file === undefined) {
      return
    }
    if (attachments.length >= 4) {
      showToast({ text: formatMessage({ id: 'alert.validation.attachment_length' }, { limit: 4 }), type: 'failure' })
      return
    }
    if (!file.type.includes('image') && !file.type.includes('video')) {
      showToast({ text: formatMessage({ id: 'alert.validation.attachment_type' }), type: 'failure' })
      return
    }
    setLoading(true)
    try {
      const res = await props.client.uploadMedia(file)
      setAttachments(current => [...current, res.data])
    } catch {
      showToast({ text: formatMessage({ id: 'alert.upload_error' }), type: 'failure' })
    } finally {
      setLoading(false)
    }
  }

  const removeFile = (index: number) => {
    setAttachments(current => current.filter((_, i) => i !== index))
  }

  const openDescription = (index: number) => {
    setEditMedia(attachments[index])
  }

  const closeDescription = () => {
    setEditMedia(undefined)
  }

  const togglePoll = () => {
    if (poll) {
      setPoll(null)
    } else {
      setPoll(defaultPoll())
    }
  }

  const onEmojiSelect = emoji => {
    const textarea = document.getElementById('body') as HTMLTextAreaElement
    const cursor = textarea.selectionStart
    if (emoji.native) {
      setBody(current => `${current.slice(0, cursor)}${emoji.native} ${current.slice(cursor)}`)
    } else if (emoji.shortcodes) {
      setBody(current => `${current.slice(0, cursor)}${emoji.shortcodes} ${current.slice(cursor)}`)
    }
    setPopoverEmoji(false)
  }

  return (
    <div className="px-4 pb-4">
      <form id="form">
        {cw && (
          <Input
            id="spoiler"
            type="text"
            color="blue"
            containerProps={{ className: 'mb-2' }}
            value={spoiler}
            onChange={ev => setSpoiler(ev.target.value)}
            placeholder={formatMessage({ id: 'compose.spoiler.placeholder' })}
          />
        )}
        <div className="relative">
          <Textarea
            id="body"
            color="blue"
            className="resize-none focus:ring-0"
            placeholder={formatMessage({ id: 'compose.placeholder' })}
            rows={3}
            value={body}
            onChange={ev => setBody(ev.target.value)}
            ref={textareaRef}
          />
          <Popover open={popoverEmoji} handler={setPopoverEmoji}>
            <PopoverHandler>
              <button className="absolute top-1 right-1 text-gray-600 cursor-pointer" title={formatMessage({ id: 'compose.emoji' })}>
                <FaFaceLaughBeam />
              </button>
            </PopoverHandler>
            <PopoverContent>
              <Picker data={data} onEmojiSelect={onEmojiSelect} previewPosition="none" set="native" perLine="7" theme="light" />
            </PopoverContent>
          </Popover>
        </div>
      </form>
      {poll && <PollForm poll={poll} setPoll={setPoll} />}
      <div className="attachments flex gap-2">
        {attachments.map((f, index) => (
          <div className="py-2 relative" key={index}>
            <button className="absolute bg-gray-600 rounded" onClick={() => removeFile(index)}>
              <FaXmark className="text-gray-200" />
            </button>
            <button className="absolute right-0 bg-gray-600 rounded" onClick={() => openDescription(index)}>
              <FaPencil className="text-gray-200" />
            </button>
            <img src={f.preview_url} style={{ width: '80px', height: '80px' }} className="rounded-md" />
          </div>
        ))}
      </div>

      {attachments.length > 0 && (
        <div>
          <Checkbox id="sensitive" label={formatMessage({ id: 'compose.nsfw' })} />
        </div>
      )}

      <div className="w-full flex justify-between mt-1 items-center h-5">
        <div className="ml-1 flex gap-3">
          <input type="file" id="file" className="hidden" ref={uploaderRef} onChange={fileChanged} />
          <IconButton
            variant="text"
            size="sm"
            onClick={selectFile}
            className="text-gray-400 hover:text-gray-600 text-base"
            title={formatMessage({ id: 'compose.actions.attachment' })}
          >
            <FaPaperclip />
          </IconButton>
          <IconButton
            variant="text"
            size="sm"
            onClick={togglePoll}
            className="text-gray-400 hover:text-gray-600 text-base"
            title={formatMessage({ id: 'compose.actions.poll' })}
          >
            <FaListCheck />
          </IconButton>
          <Popover open={popoverVisibility} handler={setPopoverVisibility}>
            <PopoverHandler>{visibilityIcon(visibility, formatMessage({ id: 'compose.actions.visibility' }))}</PopoverHandler>
            <PopoverContent>
              <List>
                <ListItem
                  onClick={() => {
                    setVisibility('public')
                    setPopoverVisibility(false)
                  }}
                >
                  <FormattedMessage id="compose.visibility.public" />
                </ListItem>
                <ListItem
                  onClick={() => {
                    setVisibility('unlisted')
                    setPopoverVisibility(false)
                  }}
                >
                  <FormattedMessage id="compose.visibility.unlisted" />
                </ListItem>
                <ListItem
                  onClick={() => {
                    setVisibility('private')
                    setPopoverVisibility(false)
                  }}
                >
                  <FormattedMessage id="compose.visibility.private" />
                </ListItem>
                <ListItem
                  onClick={() => {
                    setVisibility('direct')
                    setPopoverVisibility(false)
                  }}
                >
                  <FormattedMessage id="compose.visibility.direct" />
                </ListItem>
              </List>
            </PopoverContent>
          </Popover>

          {cw ? (
            <IconButton variant="text" size="sm" className="theme-enabled leading-4 text-base" onClick={() => setCW(false)}>
              CW
            </IconButton>
          ) : (
            <IconButton
              variant="text"
              size="sm"
              className="text-gray-400 hover:text-gray-600 leading-4 text-base"
              onClick={() => setCW(true)}
              title={formatMessage({ id: 'compose.actions.cw' })}
            >
              CW
            </IconButton>
          )}
        </div>
        <div className="mr-1 flex items-center gap-2">
          <span className="text-gray-400">{remaining}</span>
          <IconButton disabled={loading} onClick={post} variant="text" size="sm" title={formatMessage({ id: 'compose.actions.post' })}>
            <FaPaperPlane className="text-base text-gray-600" />
          </IconButton>
        </div>
      </div>
      <EditMedia media={editMedia} close={closeDescription} client={props.client} />
    </div>
  )
}

const visibilityIcon = (visibility: 'public' | 'unlisted' | 'private' | 'direct', title: string) => {
  switch (visibility) {
    case 'public':
      return (
        <IconButton variant="text" size="sm" className="text-gray-400 hover:text-gray-600  text-base" title={title}>
          <FaGlobe />
        </IconButton>
      )
    case 'unlisted':
      return (
        <IconButton variant="text" size="sm" className="text-gray-400 hover:text-gray-600 text-base" title={title}>
          <FaLockOpen />
        </IconButton>
      )
    case 'private':
      return (
        <IconButton variant="text" size="sm" className="text-gray-400 hover:text-gray-600  text-base" title={title}>
          <FaLock />
        </IconButton>
      )
    case 'direct':
      return (
        <IconButton variant="text" size="sm" className="text-gray-400 hover:text-gray-600 text-base" title={title}>
          <FaEnvelope />
        </IconButton>
      )
  }
}

const defaultPoll = () => ({
  options: ['', ''],
  expires_in: 86400,
  multiple: false
})

type PollProps = {
  poll: Poll
  setPoll: Dispatch<SetStateAction<Poll>>
}

const PollForm = (props: PollProps) => {
  const { formatMessage } = useIntl()

  const expiresList = [
    { label: formatMessage({ id: 'compose.poll.5min' }), value: 300 },
    { label: formatMessage({ id: 'compose.poll.30min' }), value: 1800 },
    { label: formatMessage({ id: 'compose.poll.1h' }), value: 3600 },
    { label: formatMessage({ id: 'compose.poll.6h' }), value: 21600 },
    { label: formatMessage({ id: 'compose.poll.1d' }), value: 86400 },
    { label: formatMessage({ id: 'compose.poll.3d' }), value: 259200 },
    { label: formatMessage({ id: 'compose.poll.7d' }), value: 604800 }
  ]

  const addOption = () => {
    props.setPoll(current =>
      Object.assign({}, current, {
        options: [...current.options, '']
      })
    )
  }

  const removeOption = (index: number) => {
    props.setPoll(current =>
      Object.assign({}, current, {
        options: current.options.filter((_, i) => i !== index)
      })
    )
  }

  const updateOption = (index: number, value: string) => {
    props.setPoll(current =>
      Object.assign({}, current, {
        options: current.options.map((original, i) => (i === index ? value : original))
      })
    )
  }

  const changeMultiple = (ev: ChangeEvent<HTMLInputElement>) => {
    console.log(ev)
    props.setPoll(current =>
      Object.assign({}, current, {
        multiple: ev.target.checked
      })
    )
  }

  const changeExpire = (value: number) => {
    props.setPoll(current =>
      Object.assign({}, current, {
        expires_in: value
      })
    )
  }

  return (
    <div className="pt-1">
      {props.poll.options.map((option, index) => (
        <div className="flex items-center gap-3 py-1" key={index}>
          {props.poll.multiple ? (
            <Checkbox disabled containerProps={{ className: 'p-1' }} />
          ) : (
            <Radio disabled containerProps={{ className: 'p-1' }} />
          )}
          <Input
            type="text"
            color="blue"
            value={option}
            onChange={ev => updateOption(index, ev.target.value)}
            containerProps={{ className: 'h-8' }}
          />
          <FaXmark className="text-gray-400 cursor-pointer" onClick={() => removeOption(index)} />
        </div>
      ))}
      <div className="flex gap-3 pt-2">
        <Button onClick={addOption} size="sm" color="indigo" variant="outlined">
          <FormattedMessage id="compose.poll.add" />
        </Button>
        <Select
          id="expires"
          color="blue"
          value={`${props.poll.expires_in}`}
          onChange={e => changeExpire(parseInt(e))}
          containerProps={{ className: 'h-8' }}
        >
          {expiresList.map((expire, index) => (
            <Option value={`${expire.value}`} key={index}>
              {expire.label}
            </Option>
          ))}
        </Select>
      </div>
      <div className="mt-2">
        <Switch checked={props.poll.multiple} onChange={v => changeMultiple(v)} label={formatMessage({ id: 'compose.poll.multiple' })} />
      </div>
    </div>
  )
}
