// src/components/notifications/Follow.svelte
<script lang="ts">
  import { Avatar } from 'flowbite-svelte'
  import type { Entity } from 'megalodon'
  import { UserSolid } from 'flowbite-svelte-icons'

  export let notification: Entity.Notification
</script>

{#if notification.account}
  <div class="border-b">
    <div class="flex items-center">
      <div class="ml-2">
        <UserSolid class="text-cyan-500 mr-2 ml-auto" strokeWidth="1" size="sm" />
      </div>
      <div class="text-gray-600">{notification.account.username} followed you</div>
    </div>
    <div class="flex">
      <div class="avatar p-2">
        <Avatar src={notification.account.avatar} rounded />
      </div>
      <div class="body">
        <div class="flex">
          <div class="text-gray-800 mr-1">
            {notification.account.display_name}
          </div>
          <div>
            @{notification.account.acct}
          </div>
        </div>
        <div>
          {notification.account.followers_count} followers
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
  .avatar {
    width: 56px;
  }

  .body {
    width: calc(100% - 56px);
  }
</style>

// renderer/components/timelines/notification/Follow.tsx
import { Avatar } from 'flowbite-react'
import { Entity } from 'megalodon'
import { FaUserPlus } from 'react-icons/fa6'
import { FormattedMessage, useIntl } from 'react-intl'
import emojify from '@/utils/emojify'

type Props = {
  notification: Entity.Notification
}

export default function Follow(props: Props) {
  const { formatMessage } = useIntl()

  return (
    <div className="border-b mr-2 py-1">
      <div className="flex items-center">
        <div style={{ width: '56px' }}>
          <FaUserPlus className="text-blue-600 w-4 mr-2 ml-auto" />
        </div>
        <div style={{ width: 'calc(100% - 56px)' }}>
          <span
            dangerouslySetInnerHTML={{
              __html: emojify(
                formatMessage(
                  {
                    id: actionId(props.notification)
                  },
                  { user: props.notification.account.username }
                ),
                props.notification.account.emojis
              )
            }}
          />
        </div>
      </div>
      <div className="flex">
        <div className="p-2" style={{ width: '56px' }}>
          <Avatar img={props.notification.account.avatar} />
        </div>
        <div style={{ width: 'calc(100% - 56px)' }}>
          <div className="flex">
            <span
              className="text-gray-950 text-ellipsis break-all overflow-hidden"
              dangerouslySetInnerHTML={{ __html: emojify(props.notification.account.display_name, props.notification.account.emojis) }}
            ></span>
            <span className="text-gray-600 text-ellipsis break-all overflow-hidden">@{props.notification.account.acct}</span>
          </div>
          <div className="text-gray-600">
            <FormattedMessage id="notification.follow.followers" values={{ num: props.notification.account.followers_count }} />
          </div>
        </div>
      </div>
    </div>
  )
}

const actionId = (notification: Entity.Notification) => {
  if (notification.type === 'follow_request') {
    return 'notification.follow_request.body'
  } else {
    return 'notification.follow.body'
  }
}
