// src/renderer/components/TimelineSpace/Cards/Notification.vue
<template>
<div id="notification">
  <favourite v-if="message.type === 'favourite'" :message="message"></favourite>
  <follow v-if="message.type === 'follow'" :message="message"></follow>
  <mention v-if="message.type === 'mention'" :message="message"></mention>
  <reblog v-if="message.type == 'reblog'" :message="message"></reblog>
</div>
</template>

<script>
import Favourite from './Notification/Favourite'
import Follow from './Notification/Follow'
import Mention from './Notification/Mention'
import Reblog from './Notification/Reblog'

export default {
  name: 'notification',
  props: ['message'],
  components: { Favourite, Follow, Mention, Reblog }
}
</script>

// src/components/notifications/Notification.svelte
<script lang="ts">
  import type { Entity } from 'megalodon'
  import Follow from './Follow.svelte'
  import Reaction from './Reaction.svelte'
  import Status from '../statuses/Status.svelte'

  export let notification: Entity.Notification
</script>

<div>
  {#if notification.type === 'follow' || notification.type === 'follow_request'}
    <Follow {notification} />
  {:else if notification.type === 'mention' && notification.status}
    <Status status={notification.status} />
  {:else if notification.type === 'favourite' || notification.type === 'reblog' || notification.type === 'quote' || notification.type === 'poll_expired' || notification.type === 'poll_vote' || notification.type === 'status' || notification.type === 'update' || notification.type === 'emoji_reaction'}
    <Reaction {notification} />
  {/if}
</div>
