// renderer/components/timelines/notification/Notification.tsx
import { Entity, MegalodonInterface } from 'megalodon'
import Status from '../status/Status'
import Reaction from './Reaction'
import Follow from './Follow'

type Props = {
  notification: Entity.Notification
  client: MegalodonInterface
  onRefresh: (status: Entity.Status) => void
}

export default function Notification(props: Props) {
  switch (props.notification.type) {
    case 'mention': {
      if (props.notification.status) {
        return <Status client={props.client} status={props.notification.status} onRefresh={props.onRefresh} />
      } else {
        return null
      }
    }
    case 'favourite':
    case 'reblog':
    case 'poll_expired':
    case 'poll_vote':
    case 'quote':
    case 'status':
    case 'update':
    case 'emoji_reaction':
    case 'reaction': {
      if (props.notification.status) {
        return <Reaction client={props.client} notification={props.notification} onRefresh={props.onRefresh} />
      } else {
        return null
      }
    }
    case 'follow':
    case 'follow_request':
      return <Follow notification={props.notification} />

    default: {
      return null
    }
  }
}

// src/components/notifications/Notification.svelte
<script lang="ts">
  import type { Entity, MegalodonInterface } from 'megalodon'
  import Follow from './Follow.svelte'
  import Reaction from './Reaction.svelte'
  import Status from '../statuses/Status.svelte'

  export let notification: Entity.Notification
  export let client: MegalodonInterface
  export let updateStatus: (id: string) => void
</script>

<div>
  {#if notification.type === 'follow' || notification.type === 'follow_request'}
    <Follow {notification} />
  {:else if notification.type === 'mention' && notification.status}
    <Status status={notification.status} onRefresh={updateStatus} {client} />
  {:else if notification.type === 'favourite' || notification.type === 'reblog' || notification.type === 'quote' || notification.type === 'poll_expired' || notification.type === 'poll_vote' || notification.type === 'status' || notification.type === 'update' || notification.type === 'emoji_reaction'}
    <Reaction {notification} {updateStatus} {client} />
  {/if}
</div>
