// renderer/components/timelines/notification/Reaction.tsx
import { Avatar } from 'flowbite-react'
import { Entity, MegalodonInterface } from 'megalodon'
import dayjs from 'dayjs'
import emojify from '@/utils/emojify'
import Body from '../status/Body'
import Poll from '../status/Poll'
import Card from '../status/Card'
import Media from '../status/Media'
import { FaBarsProgress, FaHouse, FaPenToSquare, FaRetweet, FaStar } from 'react-icons/fa6'
import { useIntl } from 'react-intl'

type Props = {
  notification: Entity.Notification
  client: MegalodonInterface
  onRefresh: (status: Entity.Status) => void
}

export default function Reaction(props: Props) {
  const status = props.notification.status
  const { formatMessage } = useIntl()

  const refresh = async () => {
    const res = await props.client.getStatus(status.id)
    props.onRefresh(res.data)
  }

  return (
    <div className="border-b mr-2 py-1">
      <div className="flex items-center">
        <div style={{ width: '56px' }}>{actionIcon(props.notification)}</div>
        <div style={{ width: 'calc(100% - 56px)' }}>
          <span
            dangerouslySetInnerHTML={{
              __html: emojify(
                formatMessage(
                  {
                    id: actionId(props.notification)
                  },
                  { user: props.notification.account.username }
                ),
                props.notification.account.emojis
              )
            }}
          />
        </div>
      </div>
      <div className="flex">
        <div className="p-2" style={{ width: '56px' }}>
          <Avatar img={status.account.avatar} />
        </div>
        <div className="text-gray-600 break-all overflow-hidden" style={{ width: 'calc(100% - 56px)' }}>
          <div className="flex justify-between">
            <div className="flex">
              <span
                className="text-gray-600 text-ellipsis break-all overflow-hidden"
                dangerouslySetInnerHTML={{ __html: emojify(status.account.display_name, status.account.emojis) }}
              ></span>
              <span className="text-gray-600 text-ellipsis break-all overflow-hidden">@{status.account.acct}</span>
            </div>
            <div className="text-gray-600 text-right">
              <time dateTime={status.created_at}>{dayjs(status.created_at).format('YYYY-MM-DD HH:mm:ss')}</time>
            </div>
          </div>
          <Body status={status} className="text-gray-600" />
          {status.poll && <Poll poll={status.poll} onRefresh={refresh} client={props.client} className="text-gray-600" />}
          {status.card && <Card card={status.card} />}
          <Media media={status.media_attachments} />
        </div>
      </div>
    </div>
  )
}

const actionIcon = (notification: Entity.Notification) => {
  switch (notification.type) {
    case 'favourite': {
      return <FaStar className="text-orange-500 w-4 mr-2 ml-auto" />
    }
    case 'reblog':
    case 'quote': {
      return <FaRetweet className="text-blue-600 w-4 mr-2 ml-auto" />
    }
    case 'poll_expired':
    case 'poll_vote': {
      return <FaBarsProgress className="text-blue-600 w-4 mr-2 ml-auto" />
    }
    case 'status': {
      return <FaHouse className="text-blue-600 w-4 mr-2 ml-auto" />
    }
    case 'update': {
      return <FaPenToSquare className="text-blue-600 w-4 mr-2 ml-auto" />
    }
    case 'emoji_reaction': {
      return <span dangerouslySetInnerHTML={{ __html: notification.emoji }} />
    }
    default:
      return null
  }
}

const actionId = (notification: Entity.Notification) => {
  switch (notification.type) {
    case 'favourite':
      return 'notification.favourite.body'
    case 'reblog':
      return 'notification.reblog.body'
    case 'quote':
      return 'notification.quote.body'
    case 'poll_expired':
      return 'notification.poll_expired.body'
    case 'poll_vote':
      return 'notification.poll.vote'
    case 'status':
      return 'notification.status.body'
    case 'update':
      return 'notification.update.body'
    case 'emoji_reqction':
      return 'notification.emoji_reaction.body'

    default:
      return ''
  }
}

// src/components/notifications/Reaction.svelte
<script lang="ts">
  import { Avatar } from 'flowbite-svelte'
  import dayjs from 'dayjs'
  import type { Entity, MegalodonInterface } from 'megalodon'
  import emojify from '@/components/utils/emojify'
  import { StarSolid, ArrowsRepeatSolid, BarsSolid, HomeSolid, PenSolid } from 'flowbite-svelte-icons'
  import Card from '../statuses/Card.svelte'
  import Attachments from '../statuses/Attachments.svelte'
  import Poll from '../statuses/Poll.svelte'
  import { _ } from 'svelte-i18n'

  export let notification: Entity.Notification
  export let client: MegalodonInterface
  export let updateStatus: (id: string) => void
</script>

{#if notification.account && notification.status}
  <div class="border-b mr-2">
    <div class="flex items-center">
      {#if notification.type === 'favourite'}
        <div class="ml-2">
          <StarSolid class="text-amber-500 mr-2 ml-auto" size="sm" />
        </div>
        <div class="text-gray-600">
          {$_('notifications.favourite', { values: { user: notification.account.username } })}
        </div>
      {:else if notification.type === 'reblog' || notification.type === 'quote'}
        <div class="ml-2">
          <ArrowsRepeatSolid class="text-blue-500 mr-2 ml-auto" size="sm" />
        </div>
        <div class="text-gray-600">
          {$_('notifications.reblog', { values: { user: notification.account.username } })}
        </div>
      {:else if notification.type === 'poll_expired' || notification.type === 'poll_vote'}
        <div class="ml-2">
          <BarsSolid class="text-blue-500 mr-2 ml-auto" size="sm" />
        </div>
        <div class="text-gray-600">
          {#if notification.type === 'poll_expired'}
            {$_('notifications.poll_expired', { values: { user: notification.account.username } })}
          {:else}
            {$_('notifications.poll_vote', { values: { user: notification.account.username } })}
          {/if}
        </div>
      {:else if notification.type === 'status'}
        <div class="ml-2">
          <HomeSolid class="mr-2 ml-auto" size="sm" />
        </div>
        <div class="text-gray-600">
          {$_('notifications.status', { values: { user: notification.account.username } })}
        </div>
      {:else if notification.type === 'update'}
        <div class="ml-2">
          <PenSolid class="text-amber-500 mr-2 ml-auto" size="sm" />
        </div>
        <div class="text-gray-600">
          {$_('notifications.update', { values: { user: notification.account.username } })}
        </div>
      {:else if notification.type === 'emoji_reaction'}
        <div class="ml-2">
          <span class="mr-2 ml-auto">
            {@html notification.emoji}
          </span>
        </div>
        <div class="text-gray-600">
          {$_('notifications.reaction', { values: { user: notification.account.username } })}
        </div>
      {/if}
    </div>
    <div class="flex">
      <div class="avatar p-2">
        <Avatar src={notification.status.account.avatar} rounded />
      </div>
      <div class="body">
        <div class="header flex justify-between">
          <div class="account-name flex">
            <span class="text-gray-600 text-ellipsis break-all overflow-hidden">
              {@html emojify(notification.status.account.display_name, notification.status.account.emojis)}</span
            >
            <span class="text-gray-600 text-ellipsis break-all overflow-hidden">@{notification.status.account.acct}</span>
          </div>
          <div class="date text-gray-600 text-right">
            <time datetime={notification.status.created_at}>
              {dayjs(notification.status.created_at).format('YYYY-MM-DD HH:mm:ss')}
            </time>
          </div>
        </div>
        <div class="body text-gray-600 break-all overflow-hidden">
          {@html emojify(notification.status.content, notification.status.emojis)}
        </div>
        {#if notification.status.poll}
          <Poll poll={notification.status.poll} onRefresh={() => notification.status && updateStatus(notification.status.id)} {client} />
        {/if}
        {#if notification.status.card}
          <Card card={notification.status.card} />
        {/if}
        {#if notification.status.media_attachments.length > 0}
          <Attachments attachments={notification.status.media_attachments} />
        {/if}
      </div>
    </div>
  </div>
{/if}

<style>
  .avatar {
    width: 56px;
  }

  .body {
    width: calc(100% - 56px);
  }
</style>
