// src/components/accounts/New.svelte
<script lang="ts">
  import { Button, Modal, Label, Input } from 'flowbite-svelte'
  import generator, { detector, type MegalodonInterface } from 'megalodon'
  import { db } from '../../db'

  export let opened: boolean
  export let closeFunc: () => void
  let domain: string
  let authorizationCode: string
  let sns: 'mastodon' | 'pleroma' | 'friendica' | 'firefish'
  let authURL: string | null = null
  let clientId: string
  let clientSecret: string
  let client: MegalodonInterface
  $: url = 'https://' + domain

  const checkDomain = async () => {
    const res = await detector(url)
    sns = res
    client = generator(sns, url)
    const appData = await client.registerApp('Whalebird', {})
    clientId = appData.client_id
    clientSecret = appData.client_secret
    authURL = appData.url
    window.ipcRenderer.invoke('open-browser', authURL)
    closeFunc()
  }

  const authorize = async () => {
    const tokenData = await client.fetchAccessToken(clientId, clientSecret, authorizationCode)
    client = generator(sns, url, tokenData.access_token, 'Whalebird')
    const acct = await client.verifyAccountCredentials()
    await db.accounts.add({
      username: acct.data.username,
      account_id: acct.data.id,
      avatar: acct.data.avatar,
      client_id: clientId,
      client_secret: clientSecret,
      access_token: tokenData.access_token,
      refresh_token: tokenData.refresh_token,
      url: url,
      domain: domain,
      sns: sns
    })
    closeFunc()
  }
</script>

<Modal title="Add account" bind:open={opened} autoclose={false} dismissable={false}>
  {#if sns === undefined}
    <form class="flex flex-col space-y-6" action="#">
      <Label class="space-y-2">
        <span>Domain</span>
        <Input type="text" name="domain" placeholder="mastodon.social" bind:value={domain} required />
      </Label>
      <Button type="submit" class="w-full1" on:click={checkDomain}>Login</Button>
    </form>
  {:else}
    <form class="flex flex-col space-y-6" action="#">
      <p>Please approve in your browser</p>
      <Label class="space-y-2">
        <span>Authorization Code</span>
        <Input type="text" name="authorizationCode" bind:value={authorizationCode} required />
      </Label>
      <Button type="submit" class="w-full1" on:click={authorize}>Authorize</Button>
    </form>
  {/if}
</Modal>

// renderer/components/accounts/New.tsx
import { Label, Modal, TextInput, Button } from 'flowbite-react'
import generator, { MegalodonInterface, detector } from 'megalodon'
import { useState } from 'react'
import { db } from '@/db'

type NewProps = {
  opened: boolean
  close: () => void
}

export default function New(props: NewProps) {
  const [sns, setSNS] = useState<'mastodon' | 'pleroma' | 'firefish' | 'friendica' | null>(null)
  const [domain, setDomain] = useState<string>('')
  const [client, setClient] = useState<MegalodonInterface>()
  const [clientId, setClientId] = useState<string>()
  const [clientSecret, setClientSecret] = useState<string>()

  const checkDomain = async () => {
    const input = document.getElementById('domain') as HTMLInputElement
    setDomain(input.value)
    const url = `https://${input.value}`
    const sns = await detector(url)
    setSNS(sns)
    const client = generator(sns, url)
    setClient(client)
    const appData = await client.registerApp('Whalebird', {})
    setClientId(appData.client_id)
    setClientSecret(appData.client_secret)
    global.ipc.invoke('open-browser', appData.url)
  }

  const authorize = async () => {
    const input = document.getElementById('authorization') as HTMLInputElement
    if (!client || !clientId || !clientSecret) return
    const tokenData = await client.fetchAccessToken(clientId, clientSecret, input.value)
    if (!sns) return
    const cli = generator(sns, `https://${domain}`, tokenData.access_token, 'Whalebird')
    const acct = await cli.verifyAccountCredentials()
    await db.accounts.add({
      username: acct.data.username,
      account_id: acct.data.id,
      avatar: acct.data.avatar,
      client_id: clientId,
      client_secret: clientSecret,
      access_token: tokenData.access_token,
      refresh_token: tokenData.refresh_token,
      url: `https://${domain}`,
      domain: domain,
      sns: sns
    })
    props.close()
  }

  return (
    <>
      <Modal dismissible={false} show={props.opened} onClose={() => props.close()}>
        <Modal.Header>Add account</Modal.Header>
        <Modal.Body>
          <form className="flex max-w-md flex-col gap-2">
            {sns === null && (
              <>
                <div className="block">
                  <Label htmlFor="domain" value="Domain" />
                </div>
                <TextInput id="domain" placeholder="mastodon.social" required type="text" />
                <Button onClick={checkDomain}>Sign In</Button>{' '}
              </>
            )}
            {sns && (
              <>
                <div className="block">
                  <Label htmlFor="authorization" value="Authorization Code" />
                </div>
                <TextInput id="authorization" required type="text" />
                <Button onClick={authorize}>Authorize</Button>{' '}
              </>
            )}
          </form>
        </Modal.Body>
      </Modal>
    </>
  )
}
