// renderer/components/timelines/status/Actions.tsx
import { Entity, MegalodonInterface } from 'megalodon'
import { FaBookmark, FaEllipsis, FaReply, FaRetweet, FaStar } from 'react-icons/fa6'

type Props = {
  status: Entity.Status
  client: MegalodonInterface
  onRefresh: () => void
}

export default function Actions(props: Props) {
  const reblog = async () => {
    if (props.status.reblogged) {
      await props.client.unreblogStatus(props.status.id)
    } else {
      await props.client.reblogStatus(props.status.id)
    }
    props.onRefresh()
  }

  const favourite = async () => {
    if (props.status.favourited) {
      await props.client.unfavouriteStatus(props.status.id)
    } else {
      await props.client.favouriteStatus(props.status.id)
    }
    props.onRefresh()
  }

  const bookmark = async () => {
    if (props.status.bookmarked) {
      await props.client.unbookmarkStatus(props.status.id)
    } else {
      await props.client.bookmarkStatus(props.status.id)
    }
    props.onRefresh()
  }

  return (
    <div className="flex gap-6">
      <FaReply className={`w-4 text-gray-400 cursor-pointer hover:text-gray-600`} />
      <FaRetweet className={`${retweetColor(props.status)} w-4 cursor-pointer hover:text-gray-600`} onClick={reblog} />
      <FaStar className={`${favouriteColor(props.status)} w-4 cursor-pointer hover:text-gray-600`} onClick={favourite} />
      <FaBookmark className={`${bookmarkColor(props.status)} w-4 cursor-pointer hover:text-gray-600`} onClick={bookmark} />
      <FaEllipsis className="w-4 text-gray-400 cursor-pointer hover:text-gray-600" />
    </div>
  )
}

const retweetColor = (status: Entity.Status) => {
  if (status.reblogged) {
    return 'text-blue-600'
  } else {
    return 'text-gray-400'
  }
}

const favouriteColor = (status: Entity.Status) => {
  if (status.favourited) {
    return 'text-orange-400'
  } else {
    return 'text-gray-400'
  }
}

const bookmarkColor = (status: Entity.Status) => {
  if (status.bookmarked) {
    return 'text-rose-500'
  } else {
    return 'text-gray-400'
  }
}

// src/components/statuses/Actions.svelte
<script lang="ts">
  import { Dropdown, DropdownItem } from 'flowbite-svelte'
  import { ArrowsRepeatSolid, BookmarkSolid, DotsHorizontalOutline, ReplySolid, StarSolid } from 'flowbite-svelte-icons'
  import type { Entity, MegalodonInterface } from 'megalodon'
  import { _ } from 'svelte-i18n'

  export let client: MegalodonInterface
  export let status: Entity.Status
  export let onRefresh: () => void

  const boost = async () => {
    if (status.reblogged) {
      await client.unreblogStatus(status.id)
    } else {
      await client.reblogStatus(status.id)
    }
    onRefresh()
  }

  const favourite = async () => {
    if (status.favourited) {
      await client.unfavouriteStatus(status.id)
    } else {
      await client.favouriteStatus(status.id)
    }
    onRefresh()
  }

  const bookmark = async () => {
    if (status.bookmarked) {
      await client.unbookmarkStatus(status.id)
    } else {
      await client.bookmarkStatus(status.id)
    }
    onRefresh()
  }

  const openInBrowser = () => {
    window.ipcRenderer.invoke('open-browser', status.url)
  }
</script>

<div>
  <button><ReplySolid class="text-gray-400 hover:text-blue-500 mr-3" size="sm" /></button>
  <button on:click={boost}>
    {#if status.reblogged}
      <ArrowsRepeatSolid class="text-blue-600 hover:text-blue-500 mr-3" size="sm" />
    {:else}
      <ArrowsRepeatSolid class="text-gray-400 hover:text-blue-500 mr-3" size="sm" />
    {/if}
  </button>
  <button on:click={favourite}>
    {#if status.favourited}
      <StarSolid class="text-orange-400 hover:text-orange-300 mr-3" size="sm" />
    {:else}
      <StarSolid class="text-gray-400 hover:text-orange-300 mr-3" size="sm" />
    {/if}
  </button>
  <button on:click={bookmark}>
    {#if status.bookmarked}
      <BookmarkSolid class="text-rose-500 hover:text-rose-400 mr-3" size="sm" />
    {:else}
      <BookmarkSolid class="text-gray-400 hover:text-rose-400 mr-3" size="sm" />
    {/if}
  </button>
  <button><DotsHorizontalOutline class="text-gray-400 hover:text-blue-500 mr-3" size="sm" /></button>
  <Dropdown>
    <DropdownItem on:click={openInBrowser}>{$_('timeline.actions.open_in_browser')}</DropdownItem>
  </Dropdown>
</div>
