// renderer/components/timelines/status/Card.tsx
import { invoke } from '@/utils/invoke'
import { Entity } from 'megalodon'

type Props = {
  card: Entity.Card
}

export default function Card(props: Props) {
  const openCard = () => {
    invoke('open-browser', props.card.url)
  }

  return (
    <div
      className="flex border-inherit border border-solid rounded-md w-full cursor-pointer overflow-hidden text-ellipsis mb-1"
      onClick={openCard}
    >
      <div style={{ height: '60px', width: '60px' }}>
        <img src={props.card.image} alt={props.card.title} className="w-full h-full" />
      </div>
      <div className="px-2" style={{ height: '60px', width: 'calc(100% - 60px)' }}>
        <p className="text-ellipsis overflow-hidden w-full whitespace-nowrap">
          <strong>{props.card.title}</strong>
        </p>
        <p className="text-ellipsis overflow-hidden w-full whitespace-nowrap">{props.card.description}</p>
      </div>
    </div>
  )
}

// src/components/statuses/Card.svelte
<script lang="ts">
  import type { Entity } from 'megalodon'

  export let card: Entity.Card

  const openCard = async () => {
    window.ipcRenderer.invoke('open-browser', card.url)
  }
</script>

<div class="w-full flex border-solid rounded-md border-inherit border overflow-hidden cursor-pointer" on:click={openCard}>
  <div class="h-20 w-20">
    <img src={card.image ?? undefined} alt={card.title} class="h-20 w-20" />
  </div>
  <div class="card px-2 py-2 h-20">
    <p class="text-ellipsis overflow-hidden w-full">
      <strong>{card.title}</strong>
    </p>
    <p class="text-ellipsis overflow-hidden w-full">
      {card.description}
    </p>
  </div>
</div>

<style>
  .card {
    width: calc(100% - 80px);
  }
</style>
