// renderer/components/timelines/status/Status.tsx
import { Avatar } from 'flowbite-react'
import { Entity, MegalodonInterface } from 'megalodon'
import dayjs from 'dayjs'
import Body from './Body'
import Media from './Media'
import emojify from '@/utils/emojify'
import Card from './Card'
import Poll from './Poll'
import { FormattedMessage } from 'react-intl'
import Actions from './Actions'

type Props = {
  status: Entity.Status
  client: MegalodonInterface
  onRefresh: (status: Entity.Status) => void
}

export default function Status(props: Props) {
  const status = originalStatus(props.status)

  const onRefresh = async () => {
    const res = await props.client.getStatus(status.id)
    props.onRefresh(res.data)
  }

  return (
    <div className="border-b mr-2 py-1">
      {rebloggedHeader(props.status)}
      <div className="flex">
        <div className="p-2" style={{ width: '56px' }}>
          <Avatar img={status.account.avatar} />
        </div>
        <div className="text-gray-950 break-all overflow-hidden" style={{ width: 'calc(100% - 56px)' }}>
          <div className="flex justify-between">
            <div className="flex">
              <span
                className="text-gray-950 text-ellipsis break-all overflow-hidden"
                dangerouslySetInnerHTML={{ __html: emojify(status.account.display_name, status.account.emojis) }}
              ></span>
              <span className="text-gray-600 text-ellipsis break-all overflow-hidden">@{status.account.acct}</span>
            </div>
            <div className="text-gray-600 text-right">
              <time dateTime={status.created_at}>{dayjs(status.created_at).format('YYYY-MM-DD HH:mm:ss')}</time>
            </div>
          </div>
          <Body status={status} />
          {status.poll && <Poll poll={status.poll} onRefresh={onRefresh} client={props.client} />}
          {status.card && <Card card={status.card} />}
          <Media media={status.media_attachments} />
          <Actions />
        </div>
      </div>
    </div>
  )
}

const originalStatus = (status: Entity.Status) => {
  if (status.reblog && !status.quote) {
    return status.reblog
  } else {
    return status
  }
}

const rebloggedHeader = (status: Entity.Status) => {
  if (status.reblog && !status.quote) {
    return (
      <div className="flex text-gray-600">
        <div className="grid justify-items-end pr-2" style={{ width: '56px' }}>
          <Avatar img={status.account.avatar} size="xs" />
        </div>
        <div style={{ width: 'calc(100% - 56px)' }}>
          <FormattedMessage id="timeline.status.boosted" values={{ user: status.account.username }} />
        </div>
      </div>
    )
  } else {
    return null
  }
}

// src/components/statuses/Status.svelte
<script lang="ts">
  import { Avatar } from 'flowbite-svelte'
  import type { Entity, MegalodonInterface } from 'megalodon'
  import dayjs from 'dayjs'
  import emojify from '@/components/utils/emojify'
  import Card from './Card.svelte'
  import Attachments from './Attachments.svelte'
  import Poll from './Poll.svelte'
  import Actions from './Actions.svelte'

  export let status: Entity.Status
  export let client: MegalodonInterface
  export let onRefresh: (id: string) => void
  $: originalStatus = status.reblog && !status.quote ? status.reblog : status
</script>

<div class="border-b mr-2 py-1">
  {#if status.reblog && !status.quote}
    <div class="flex">
      <div class="avatar grid justify-items-end pr-2">
        <Avatar src={status.account.avatar} rounded size="xs" />
      </div>
      <div class="status">
        {status.account.username} boosted
      </div>
    </div>
  {/if}
  <div class="flex">
    <div class="avatar p-2">
      <Avatar src={originalStatus.account.avatar} rounded />
    </div>
    <div class="status relative">
      <div class="header flex justify-between">
        <div class="account-name flex">
          <span class="text-gray-950 text-ellipsis break-all overflow-hidden">
            {@html emojify(originalStatus.account.display_name, originalStatus.account.emojis)}</span
          >
          <span class="text-gray-600 text-ellipsis break-all overflow-hidden">@{originalStatus.account.acct}</span>
        </div>
        <div class="date text-gray-600 text-right">
          <time datetime={originalStatus.created_at}>
            {dayjs(originalStatus.created_at).format('YYYY-MM-DD HH:mm:ss')}
          </time>
        </div>
      </div>
      <div class="body text-gray-950 break-all overflow-hidden">
        {@html emojify(originalStatus.content, originalStatus.emojis)}
      </div>
      {#if originalStatus.poll}
        <Poll poll={originalStatus.poll} onRefresh={() => onRefresh(status.id)} {client} />
      {/if}
      {#if originalStatus.card}
        <Card card={originalStatus.card} />
      {/if}
      {#if originalStatus.media_attachments.length > 0}
        <Attachments attachments={originalStatus.media_attachments} />
      {/if}
      <Actions />
    </div>
  </div>
</div>

<style>
  .avatar {
    width: 56px;
  }

  .status {
    width: calc(100% - 56px);
  }
</style>
